### ISSUE TITLE
Markdown syntax not rendered in task titles

### ISSUE THREAD

**Issue by approximate** [SuperChamp234/habitica-sync#15]
When markdown is used in the task title, the plugin doesn't render it at all, the plain text version is shown instead.

![image](https://user-images.githubusercontent.com/1837916/142404206-cfeecf43-7f37-405c-a705-5e2026920303.png)

I realize this doesn't necesserily mean it's a bug - maybe there's no "correct" way to marry Habitica's markdown to Obsidian renderer (or maybe there is, but it produces weird or ugly results). But at least this deserves to be documented.

**Comment by SuperChamp234** [comment]
This indeed deserves to be documented, We'll see what we can do till the time.
