### ISSUE TITLE
Please implement entry notes support

### ISSUE THREAD

**Issue by approximate** [SuperChamp234/habitica-sync#16]
Currently the plugin only renders the entry title. 

I, and many others, also use notes quite a lot, like this:
![image](https://user-images.githubusercontent.com/1837916/142405068-1c75f5be-87fd-42cc-8e4c-581dda940ffa.png)

Habitica website renders it like this:
![image](https://user-images.githubusercontent.com/1837916/142404999-bca0b9d6-439e-4367-8043-9b363fabd5da.png)

It would be cool if you could implement this as well, possibly as a toggle in the plugin settings in case the user prefers to see the titles only.

Edit: typos

**Comment by SuperChamp234** [comment]
This is under implementation and will be released in the next update, credit to @kkzzhizhou for helping!
