### ISSUE TITLE
Daily tasks are missing the "Due" state

### ISSUE THREAD

**Issue by ebdavison** [SuperChamp234/habitica-sync#22]
On Habitica, Daily tasks are not all due every day.  The ones that need to be done that day are "Due" and the rest are "Not Due":

![image](https://user-images.githubusercontent.com/549431/149152587-46292b75-02c8-4ce9-9c99-a35de82923a5.png)

In the Obsidian tab, there are "Active" and "Completed".  

![image](https://user-images.githubusercontent.com/549431/149152725-d4fce6c1-4165-49cf-aa6a-a28f7bc4ac0e.png)

It would be less confusing in Obsidian if "Due" tasks could be implemented.

**Comment by SuperChamp234** [comment]
Thanks for bringing it to our attention! We've fixed it and will release asap!
![image](https://user-images.githubusercontent.com/40035606/149516531-f5ab0696-81d5-4a7e-a326-ad1361a39c6b.png)
