### ISSUE TITLE
Please add sub-tasks to the To Do list

### ISSUE THREAD

**Issue by ebdavison** [SuperChamp234/habitica-sync#23]
On Habitica website, To Do items can have sub-tasks, e.g.:

![image](https://user-images.githubusercontent.com/549431/149157128-dfce6111-fe1f-4df2-a4a0-2876dfcb2791.png)

Please add support for these to the Obsidian UI.

**Comment by SuperChamp234** [comment]
![image](https://user-images.githubusercontent.com/40035606/149516073-8a9adad2-505d-4431-93d2-40ad1a7b5193.png)
Yes! I it is in working right now, we'll release soon!

**Comment by ransurf** [comment]
Not sure why this wasn't closed as resolved
